using System.ComponentModel;
using System.Runtime.CompilerServices;
using MyVpn.Core.Results;
using MyVpn.UI.Localization;

namespace MyVpn.UI.ViewModels;

/// <summary>Minimal observable base for the view models.</summary>
/// <remarks>
/// Hand-written rather than generated by the MVVM toolkit's source generator, matching the
/// existing view model: the property count is small enough that the generator's indirection
/// buys nothing, and a plain base class keeps the observable contract obvious.
/// </remarks>
public abstract class ObservableObject : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName] string? propertyName = null) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    /// <summary>
    /// Signals that every bound property changed.
    /// </summary>
    /// <remarks>
    /// Used on a language switch. An empty property name tells the binding layer to re-read the
    /// whole view model, which is what makes the switch take effect without rebuilding the window.
    /// </remarks>
    protected void OnAllPropertiesChanged() => OnPropertyChanged(string.Empty);

    protected bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value))
        {
            return false;
        }

        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}

/// <summary>One label/value row in a detail table.</summary>
/// <remarks>
/// Mutable and observable so that a language switch updates the rows in place. Replacing the
/// collection instead would rebuild the whole list on every state change, which on a fast
/// connect/disconnect sequence is visibly flickery.
/// </remarks>
public sealed class DetailRow : ObservableObject
{
    private string _label;
    private string _value;

    public DetailRow(string label, string value)
    {
        _label = label;
        _value = value;
    }

    public string Label
    {
        get => _label;
        set => SetField(ref _label, value);
    }

    public string Value
    {
        get => _value;
        set => SetField(ref _value, value);
    }

    public void Set(string label, string value)
    {
        Label = label;
        Value = value;
    }
}

/// <summary>Renders structured failures and diagnostics through the localization catalog.</summary>
/// <remarks>
/// Message keys are resolved here and nowhere else. Nothing in this project composes a
/// user-facing sentence by hand: a new string in the UI must arrive as a key, which is what keeps
/// the catalogs authoritative and the technical detail out of the window.
/// </remarks>
internal static class Presentation
{
    /// <summary>Message key for "unknown", used wherever a fact was not established.</summary>
    public const string UnknownKey = "error.xray.version_unknown";

    /// <summary>Resolves an error's message, substituting its arguments.</summary>
    public static string Describe(LocalizationService localization, MyVpnError error)
    {
        ArgumentNullException.ThrowIfNull(localization);
        ArgumentNullException.ThrowIfNull(error);
        return localization.Describe(error);
    }

    /// <summary>
    /// Title line for a structured error: its severity and the localized message.
    /// </summary>
    /// <remarks>
    /// The severity is part of the title rather than the message because the same message can be
    /// a warning on one path and an error on another, and a user skimming the window needs to see
    /// which one they are looking at before reading the sentence.
    /// </remarks>
    public static string DescribeWithSeverity(LocalizationService localization, MyVpnError error) =>
        $"{SeverityWord(localization, error.Severity)}: {Describe(localization, error)}";

    /// <summary>Localized name of an error severity.</summary>
    /// <remarks>
    /// Two words only: the catalog has no standalone "error"/"critical" noun, and the connection
    /// vocabulary already carries the distinction — <c>status.degraded</c> is exactly "usable but
    /// something is wrong", which is what <see cref="ErrorSeverity.Warning"/> means here, and
    /// <c>status.faulted</c> is the state in which nothing can be trusted to work.
    /// </remarks>
    public static string SeverityWord(LocalizationService localization, ErrorSeverity severity) =>
        severity == ErrorSeverity.Warning
            ? localization.Get("status.degraded")
            : localization.Get("status.faulted");

    /// <summary>Resolves a raw message key together with its arguments.</summary>
    public static string DescribeKey(
        LocalizationService localization,
        string messageKey,
        IReadOnlyDictionary<string, string>? args = null) =>
        localization.Format(
            localization.Get(messageKey),
            (args ?? new Dictionary<string, string>(StringComparer.Ordinal))
                .Select(pair => (pair.Key, pair.Value))
                .ToArray());

    /// <summary>Labels for the optional diagnostic argument dictionaries.</summary>
    public static string ArgsText(IReadOnlyDictionary<string, string>? args) =>
        args is null || args.Count == 0
            ? string.Empty
            : string.Join(", ", args.Select(pair => $"{pair.Key}={pair.Value}"));
}

/// <summary>Formats values for display without hard-coded strings.</summary>
internal static class DisplayFormat
{
    /// <summary>
    /// Milliseconds as an integer, or the empty string when there is no measurement.
    /// </summary>
    /// <remarks>
    /// Deliberately never <c>0 ms</c> for "not measured": a latency of zero is a claim, and a
    /// user reading it would believe the tunnel was fast rather than unmeasured.
    /// </remarks>
    public static string Milliseconds(TimeSpan? value) =>
        value is null
            ? string.Empty
            : string.Format(
                System.Globalization.CultureInfo.InvariantCulture,
                "{0:0} ms",
                value.Value.TotalMilliseconds);
}
